# =============================================================================
# ConvUNeXt — PyTorch (.pth) to ONNX Conversion Script
#
# Configure the paths in CELL 1 below, then run:
#     python convunext_to_onnx.py
#
# The script reads backbone, num_classes, and img_size directly from the
# checkpoint — no manual configuration of model architecture is needed.
#
# Output : a single .onnx file saved to the path specified in ONNX_OUTPUT.
# =============================================================================

import os
import timm
import numpy as np
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 1 — Configure paths here  ← ONLY SECTION YOU NEED TO EDIT        ║
# ╚══════════════════════════════════════════════════════════════════════════╝

# Path to the .pth checkpoint generated by the Colab training script
PTH_CHECKPOINT = r"F:\Traditional Machine learning project\convunext\convunext_3cls_best.pth"

# Path where the converted .onnx file will be saved
ONNX_OUTPUT = r"F:\Traditional Machine learning project\convunext\convunext_cls_best_gis.onnx"

# Opset version for ONNX export.
# 17 is safe for all standard PyTorch ops including bilinear interpolation.
ONNX_OPSET = 18 # 17 give a runtime error

# If True  → runs a numerical verification after export:
#   feeds the same dummy input to both the PyTorch model and the ONNX model
#   and checks that outputs are numerically close (tolerance 1e-4).
# Requires: pip install onnxruntime
VERIFY_AFTER_EXPORT = True


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 2 — Model Architecture  (identical to training + test scripts)    ║
# ╚══════════════════════════════════════════════════════════════════════════╝
class ConvBnAct(nn.Module):
    def __init__(self, in_ch, out_ch, kernel=3, act=True):
        super().__init__()
        self.block = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel,
                      padding=kernel // 2, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.GELU() if act else nn.Identity(),
        )
    def forward(self, x):
        return self.block(x)


class DecoderBlock(nn.Module):
    def __init__(self, in_ch, skip_ch, out_ch):
        super().__init__()
        self.up   = nn.Upsample(scale_factor=2, mode="bilinear",
                                 align_corners=False)
        self.conv = nn.Sequential(
            ConvBnAct(in_ch + skip_ch, out_ch),
            ConvBnAct(out_ch, out_ch),
        )

    def forward(self, x, skip=None):
        x = self.up(x)
        if skip is not None:
            if x.shape[-2:] != skip.shape[-2:]:
                x = F.interpolate(x, size=skip.shape[-2:],
                                  mode="bilinear", align_corners=False)
            x = torch.cat([x, skip], dim=1)
        return self.conv(x)


class ConvUNeXt(nn.Module):
    def __init__(self, backbone: str = "convnext_small",
                 pretrained: bool = False,
                 num_classes: int = 3):
        super().__init__()
        # pretrained=False — weights come from the checkpoint
        self.encoder = timm.create_model(
            backbone, pretrained=pretrained,
            features_only=True, out_indices=(0, 1, 2, 3),
        )
        enc_chs    = self.encoder.feature_info.channels()
        bottleneck = enc_chs[-1]
        # No cap — must match training exactly
        dec_chs    = [
            bottleneck // 2,
            bottleneck // 4,
            bottleneck // 8,
            bottleneck // 16,
        ]
        self.dec4 = DecoderBlock(enc_chs[3], enc_chs[2], dec_chs[0])
        self.dec3 = DecoderBlock(dec_chs[0], enc_chs[1], dec_chs[1])
        self.dec2 = DecoderBlock(dec_chs[1], enc_chs[0], dec_chs[2])
        self.dec1 = DecoderBlock(dec_chs[2], 0,          dec_chs[3])
        self.head = nn.Sequential(
            ConvBnAct(dec_chs[3], dec_chs[3]),
            nn.Conv2d(dec_chs[3], num_classes, kernel_size=1),
        )

    def forward(self, x):
        H, W           = x.shape[-2:]
        s0, s1, s2, s3 = self.encoder(x)
        d4 = self.dec4(s3, s2)
        d3 = self.dec3(d4, s1)
        d2 = self.dec2(d3, s0)
        d1 = self.dec1(d2)
        return F.interpolate(self.head(d1), size=(H, W),
                             mode="bilinear", align_corners=False)


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 3 — Load Checkpoint                                               ║
# ╚══════════════════════════════════════════════════════════════════════════╝
def load_model():
    """
    Reads backbone, num_classes, and img_size from the checkpoint metadata.
    Returns (model, img_size, num_classes) fully on CPU in eval mode.
    """
    if not Path(PTH_CHECKPOINT).exists():
        raise FileNotFoundError(f"Checkpoint not found: {PTH_CHECKPOINT}")

    # Always load to CPU for ONNX export — ONNX export must run on CPU
    ckpt = torch.load(PTH_CHECKPOINT, map_location="cpu")

    backbone    = ckpt.get("backbone",    "convnext_small")
    num_classes = ckpt.get("num_classes", None)
    img_size    = ckpt.get("img_size",    None)
    epoch       = ckpt.get("epoch",       "?")
    val_loss    = ckpt.get("val_loss",    float("nan"))

    if num_classes is None:
        raise KeyError(
            "'num_classes' key missing from checkpoint. "
            "Re-train with the updated Colab script that saves this field."
        )
    if img_size is None:
        raise KeyError(
            "'img_size' key missing from checkpoint. "
            "Re-train with the updated Colab script that saves this field."
        )

    print(f"  📦 Checkpoint  : {PTH_CHECKPOINT}")
    print(f"  🧠 Backbone    : {backbone}")
    print(f"  🔢 Classes     : {num_classes}")
    print(f"  📐 IMG_SIZE    : {img_size}")
    print(f"  📅 Saved epoch : {epoch}   val_loss = {val_loss:.4f}")

    model = ConvUNeXt(backbone=backbone, pretrained=False,
                      num_classes=num_classes)
    model.load_state_dict(ckpt["model_state"])
    model.eval()   # critical: sets BatchNorm to use running stats, not batch stats

    return model, img_size, num_classes


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 4 — Export to ONNX                                                ║
# ╚══════════════════════════════════════════════════════════════════════════╝
def export_to_onnx(model: ConvUNeXt, img_size: int, num_classes: int):
    """
    Traces the model with a dummy input and writes the ONNX graph to disk.

    The exported model has:
        Input  name : "image"   shape : (1, 3, img_size, img_size)
        Output name : "logits"  shape : (1, num_classes, img_size, img_size)

    Dynamic axes are NOT used — the input resolution is fixed to img_size.
    This matches the fixed-size inference used in convunext_test.py.
    """
    Path(ONNX_OUTPUT).parent.mkdir(parents=True, exist_ok=True)

    # Dummy input — same shape the model sees during inference
    # batch size fixed to 1 for deployment
    dummy_input = torch.randn(1, 3, img_size, img_size)

    print(f"\n  📤 Exporting to ONNX …")
    print(f"     Input shape  : {tuple(dummy_input.shape)}")
    print(f"     Opset        : {ONNX_OPSET}")
    print(f"     Output path  : {ONNX_OUTPUT}")

    with torch.no_grad():
        torch.onnx.export(
            model,
            dummy_input,
            ONNX_OUTPUT,

            # Names shown in ONNX graph nodes
            input_names  = ["image"],
            output_names = ["logits"],

            # opset_version 17 covers all ops used (Conv, BatchNorm,
            # Upsample with bilinear, GELU, Resize, Concat)
            opset_version = ONNX_OPSET,

            # export_params=True embeds all trained weights into the .onnx file
            export_params = True,

            # do_constant_folding folds constant sub-expressions at export time
            # (e.g. fixed reshape dimensions) — reduces model size and speeds
            # up inference
            do_constant_folding = True,

            # verbose=False keeps the export log clean
            verbose = False,
        )

    file_mb = Path(ONNX_OUTPUT).stat().st_size / (1024 ** 2)
    print(f"  ✅ Export complete — {file_mb:.1f} MB")


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 5 — ONNX Graph Validation                                         ║
# ╚══════════════════════════════════════════════════════════════════════════╝
def validate_onnx_graph():
    """
    Uses the official onnx library to check that the exported graph is
    well-formed — catches malformed nodes, missing initializers, and
    shape inference errors.  Does NOT require onnxruntime.
    """
    try:
        import onnx
    except ImportError:
        print("  ⚠️  'onnx' not installed — skipping graph validation.")
        print("       Install with: pip install onnx")
        return

    model_onnx = onnx.load(ONNX_OUTPUT)
    try:
        onnx.checker.check_model(model_onnx)
        print("  ✅ ONNX graph validation passed.")
    except onnx.checker.ValidationError as e:
        print(f"  ❌ ONNX graph validation failed: {e}")
        raise


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 6 — Numerical Verification  (requires onnxruntime)               ║
# ╚══════════════════════════════════════════════════════════════════════════╝
def verify_outputs(model: ConvUNeXt, img_size: int):
    """
    Runs the same random input through:
        1. The original PyTorch model (on CPU)
        2. The exported ONNX model via onnxruntime

    Asserts that every output value is within tolerance 1e-4.
    This catches any numerical divergence introduced during tracing or
    constant folding.
    """
    try:
        import onnxruntime as ort
    except ImportError:
        print("  ⚠️  'onnxruntime' not installed — skipping numerical check.")
        print("       Install with: pip install onnxruntime")
        return

    print("\n  🔍 Numerical verification …")

    # Fix the random seed so both runs see identical input
    torch.manual_seed(0)
    np.random.seed(0)
    dummy = torch.randn(1, 3, img_size, img_size)

    # ── PyTorch output ────────────────────────────────────────────────────
    with torch.no_grad():
        pt_out = model(dummy).numpy()

    # ── ONNX Runtime output ───────────────────────────────────────────────
    sess_opts = ort.SessionOptions()
    sess_opts.intra_op_num_threads = 1   # single-core, mirrors test script
    sess_opts.inter_op_num_threads = 1

    session  = ort.InferenceSession(
        ONNX_OUTPUT,
        sess_options   = sess_opts,
        providers      = ["CPUExecutionProvider"],
    )
    ort_out  = session.run(
        ["logits"],
        {"image": dummy.numpy()}
    )[0]

    # ── Compare ───────────────────────────────────────────────────────────
    max_diff = float(np.abs(pt_out - ort_out).max())
    mean_diff = float(np.abs(pt_out - ort_out).mean())

    print(f"     Max  absolute difference : {max_diff:.6f}")
    print(f"     Mean absolute difference : {mean_diff:.6f}")

    tolerance = 1e-4
    if max_diff < tolerance:
        print(f"  ✅ Outputs match within tolerance ({tolerance}).")
    else:
        print(f"  ❌ Outputs diverge — max diff {max_diff:.6f} "
              f"exceeds tolerance {tolerance}.")
        raise RuntimeError(
            "ONNX output does not match PyTorch output. "
            "The exported model may be incorrect."
        )


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 7 — Summary                                                       ║
# ╚══════════════════════════════════════════════════════════════════════════╝
def print_summary(img_size: int, num_classes: int):
    print("\n" + "=" * 56)
    print("  Export Summary")
    print("=" * 56)
    print(f"  Source  : {PTH_CHECKPOINT}")
    print(f"  Output  : {ONNX_OUTPUT}")
    print(f"  Input   : (1, 3, {img_size}, {img_size})  — float32")
    print(f"  Output  : (1, {num_classes}, {img_size}, {img_size})  — float32 logits")
    print(f"  Opset   : {ONNX_OPSET}")
    print()
    print("  To run inference with the ONNX model:")
    print()
    print("    import onnxruntime as ort, numpy as np")
    print(f"    sess  = ort.InferenceSession(r'{ONNX_OUTPUT}')")
    print(f"    inp   = np.random.randn(1, 3, {img_size}, {img_size}).astype(np.float32)")
    print("    out   = sess.run(['logits'], {'image': inp})[0]")
    print("    pred  = out.argmax(axis=1)   # shape (1, H, W)")
    print("=" * 56 + "\n")


# ╔══════════════════════════════════════════════════════════════════════════╗
# ║  CELL 8 — Entry Point                                                   ║
# ╚══════════════════════════════════════════════════════════════════════════╝
def main():
    print("\n" + "=" * 56)
    print("  ConvUNeXt — PTH → ONNX Conversion")
    print("=" * 56)

    # Load model from checkpoint
    model, img_size, num_classes = load_model()

    # Export
    export_to_onnx(model, img_size, num_classes)

    # Validate graph structure
    validate_onnx_graph()

    # Optional: verify outputs numerically against onnxruntime
    if VERIFY_AFTER_EXPORT:
        verify_outputs(model, img_size)

    # Print usage summary
    print_summary(img_size, num_classes)


if __name__ == "__main__":
    main()
